import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Urbanist} from "next/font/google"
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider"
import Products from "@/components/Products";


const urbanist = Urbanist({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Bursetk Coffe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} ${urbanist.className} antialiased`}>
           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar/>

        

        

        {children}
        

        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
